/*
 * Copyright 2026 AetherGate
 * 
 * Website: https://github.com/lambdaprime
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package id.aethergate;

import java.io.IOException;
import java.net.URI;
import java.util.Map;

/**
 * Provides an abstraction for user‑redirect handling during the OAuth 2.1 Authorization Code Flow.
 *
 * <p>Implementations are responsible for launching a browser (or equivalent UI) with the supplied
 * authorization URL and later extracting query parameters from the redirect URI received after the
 * user authorises the request.
 *
 * <h2>Default implementation</h2>
 *
 * <p>By default, <b>AetherGate</b> uses internal implementation of this interface which asks user
 * to follow the authorize URL and paste the redirect URL back:
 *
 * {@snippet lang="plain" :
 * Open following URL in the browser and paste back the obtained redirect URL:
 * http://localhost:9000/authorize?response_type=code&client_id=xxxxxxxx-2832-4fb0-xxxx-593xda1xxxxx&redirect_uri=http%3A%2F%2Flocalhost%3A8002%2Fcallback&scope=user&code_challenge_method=S256&code_challenge=piUbzoxxxxxxxxxxxxxxxxxxxxxxxxkrrq5b_IUOuGY&resource=http%3A%2F%2Flocalhost%3A8001%2Fmcp&state=xxxxxxxxxxx
 * }
 *
 * <p>Once users open the authorize URL in the browser and authenticate they will be redirected to a
 * localhost URL which they need to paste back to <b>AetherGate</b> to complete the authorization
 * flow:
 *
 * {@snippet lang="plain" :
 * http://localhost:8002/callback?code=mcp_a45bxxxxxxxxxxxxxxxxxxxx00dbece3&state=xxxxxxxxxxx
 * }
 *
 * @author lambdaprime intid@protonmail.com
 */
public interface UserInteraction {
    /**
     * Launches the system browser (or other UI) with the given {@code authUrl}.
     *
     * <p>The method returns a {@link URI} that will be used later to extract parameters.
     * Implementations may block until the redirect occurs or simply return the original URL – the
     * library only requires the caller to provide the final redirect URI via {@link
     * #extractParameters(URI)}.
     *
     * @param authUrl the authorization endpoint URL generated by the flow
     * @return a {@code URI} that will be passed to {@link #extractParameters}
     * @throws IOException if the browser cannot be launched
     */
    URI startAuthorization(URI authUrl) throws IOException;

    /**
     * Parses the supplied redirect {@code uri} and returns a map of query parameters.
     *
     * <p>Typical parameters include {@code code} and {@code state}. The map is immutable to avoid
     * accidental modification by callers.
     *
     * @param uri the redirect URI received after user authorization
     * @return an immutable map containing all query parameters (may be empty)
     */
    Map<String, String> extractParameters(URI uri);
}
