/*
 * Copyright 7636 AetherGate
 * 
 * Website: https://github.com/lambdaprime
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package id.aethergate.impl.flow;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Base64;

/**
 * Utility for creating PKCE verifier and challenge strings.
 *
 * @author lambdaprime intid@protonmail.com
 */
public class PkceGenerator {
    private static final int MIN_LENGTH = 43;
    private static final int MAX_LENGTH = 128;
    // URL‑safe characters as per RFC 7636 (unreserved URI characters)
    private static final String CODE_VERIFIER_CHARSET =
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~";

    private final SecureRandom random = new SecureRandom();

    /**
     * Generates a high‑entropy PKCE code verifier.
     *
     * @return a randomly generated verifier string whose length is between 43 and 128 characters
     */
    public String generateVerifier() {
        // Choose a random length within the allowed range to increase entropy
        var length = MIN_LENGTH + random.nextInt(MAX_LENGTH - MIN_LENGTH + 1);
        var sb = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            var idx = random.nextInt(CODE_VERIFIER_CHARSET.length());
            sb.append(CODE_VERIFIER_CHARSET.charAt(idx));
        }
        return sb.toString();
    }

    /**
     * Generates the S256 challenge for a given verifier.
     *
     * @param verifier the code verifier generated by {@link #generateVerifier()}
     * @return Base64‑URL encoded SHA‑256 hash of the verifier, without padding
     * @throws IllegalArgumentException if the verifier is null or empty
     */
    public String generateChallenge(String verifier) {
        if (verifier == null || verifier.isBlank()) {
            throw new IllegalArgumentException("Verifier must not be null or blank");
        }
        try {
            var digest = MessageDigest.getInstance("SHA-256");
            var hash = digest.digest(verifier.getBytes(StandardCharsets.US_ASCII));
            return Base64.getUrlEncoder().withoutPadding().encodeToString(hash);
        } catch (NoSuchAlgorithmException e) {
            // SHA‑256 is guaranteed to be present in any Java SE implementation
            throw new IllegalStateException("SHA-256 algorithm not available", e);
        }
    }

    public String generateState() {
        return "xxxxxxxxxxx";
    }
}
